#!/bin/bash

# you need to echo padding for all sides (even if zero) into these temp files
#   (e.g. /tmp/tpad, /tmp/tpre, etc.) in your BSPWM config for this script to
#   work. I have this:
###---bspwmrc---###
# TPAD=$(dpi 38); echo $TPAD > /tmp/tpre
# RPAD=$(dpi 0);  echo $RPAD > /tmp/rpre
# BPAD=$(dpi 0);  echo $BPAD > /tmp/bpre
# LPAD=$(dpi 0);  echo $LPAD > /tmp/lpre
###-------------###

TPRE=$(cat /tmp/tpre);
RPRE=$(cat /tmp/rpre);
BPRE=$(cat /tmp/bpre);
LPRE=$(cat /tmp/lpre);

bspc config -d focused top_padding      $TPRE
bspc config -d focused right_padding    $RPRE
bspc config -d focused bottom_padding   $BPRE
bspc config -d focused left_padding     $LPRE
