#!/usr/bin/env sh
set -e
scriptdir="$(dirname $0)"
pkgdir="$scriptdir"/packages

[ "$(id -u)" -ne 0 ] && echo "error: run as root" && return 1

[ -z "$1" ] && echo "error: specify which configuration to build" && return 1

if [ "$1" != "pc" ] && [ "$1" != "thinkpad" ]; then
    echo "error: no such configuration '$1'" && return 1
fi
conf="$1"

[ ! -d "$pkgdir" ] && echo "error: no directory '$pkgdir'" && return 1
[ ! -f "$pkgdir"/common ] && echo "error: no file '$pkgdir/common'" && return 1
[ ! -f "$pkgdir"/"$conf" ] && echo "error: no file '$pkgdir/$conf'" && return 1

pkgs() {
    grep -v "^#" "$1"
}

pkgs "$pkgdir"/common
pkgs "$pkgdir"/"$conf"

echo "Done!"
