#!/usr/bin/env sh

# https://wiki.alpinelinux.org/wiki/Suspend_on_LID_close

mkdir -p /etc/acpi/LID/
touch /etc/acpi/LID/00000080
cat << EOF > /etc/acpi/LID/00000080
#!/bin/sh
exec zzz
EOF

chmod +x /etc/acpi/LID/00000080

# kmonad

modprobe uinput
addgroup -S uinput || echo -n
addgroup felix uinput

cat << EOF > /etc/init.d/kmonad
#!/sbin/openrc-run
command="/home/felix/.local/bin/kmonad"
command_args="/home/felix/.config/kmonad/thinkpad.kbd"
command_background=true
pidfile="/var/run/${RC_SVCNAME}.pid"
EOF

chmod +x /etc/init.d/kmonad
rc-update add kmonad default
