#!/usr/bin/env sh

# Description: Set the selected image as wallpaper using nitrogen or pywal.
#
# Usage: Hover on an image and run the script to set it as wallpaper.
#
# Shell: POSIX compliant
# Author: juacq97

if [ -n "$1" ]; then
	if [ "$(file --mime-type "$1" | awk '{print $NF}' | awk -F '/' '{print $1}')" = "image" ]; then
        if type swaybg >/dev/null 2>&1; then
            pkill swaybg
            swaybg -m fill -i "$1" >/dev/null &
            disown
        else
            printf "swaybg missing"
            read -r _
        fi

    # If you want a system notification, uncomment the next 3 lines.
    # notify-send -a "nnn" "Wallpaper changed!"
    #   else
    # notify-send -a "nnn" "No image selected"
    fi
fi
