bar:
  height: 60
  location: bottom
  font: $(wq fontsans):pixelsize=30
  foreground: $(wqs foreground)ff
  background: $(wqs background)ff

  right:
    - clock:
        content:
          - string: {text: "{time}"}
