#!/usr/bin/env sh

MOD="$2"
ALT="$3"

RESIZEWINAMOUNT="100px"

if [ "$1" = "qwerty" ]; then
    LEFT='h'
    DOWN='j'
    UP='k'
    RIGHT='l'

    RETURN="Semicolon"
    SCRATCH="n"

    SPLITV='u'
    SPLITH='o'

elif [ "$1" = "colemak" ]; then
    LEFT='m'
    DOWN='n'
    UP='e'
    RIGHT='i'

    RETURN='o'
    SCRATCH="h"

    SPLITV='l'
    SPLITH='y'
else
    echo "Valid options: qwerty, colemak" && exit
fi

swaymsg "bindsym $MOD+$SPLITH splith" &
swaymsg "bindsym $MOD+$SPLITV splitv" &
swaymsg "bindsym $MOD+$RETURN exec $TERMINAL" &
swaymsg "bindsym $MOD+$LEFT focus left" &
swaymsg "bindsym $MOD+$DOWN focus down" &
swaymsg "bindsym $MOD+$UP focus up" &
swaymsg "bindsym $MOD+$RIGHT focus right" &
swaymsg "bindsym $MOD+Shift+$LEFT move left $RESIZEWINAMOUNT" &
swaymsg "bindsym $MOD+Shift+$DOWN move down $RESIZEWINAMOUNT" &
swaymsg "bindsym $MOD+Shift+$UP move up $RESIZEWINAMOUNT" &
swaymsg "bindsym $MOD+Shift+$RIGHT move right $RESIZEWINAMOUNT" &
swaymsg "bindsym $MOD+Control+t splitt" &
swaymsg "bindsym $MOD+$ALT+$LEFT  resize shrink width  $RESIZEWINAMOUNT" &
swaymsg "bindsym $MOD+$ALT+$DOWN  resize grow   height $RESIZEWINAMOUNT" &
swaymsg "bindsym $MOD+$ALT+$UP    resize shrink height $RESIZEWINAMOUNT" &
swaymsg "bindsym $MOD+$ALT+$RIGHT resize grow   width  $RESIZEWINAMOUNT" &
swaymsg "bindsym $MOD+Shift+$SCRATCH move scratchpad" &
swaymsg "bindsym $MOD+$SCRATCH scratchpad show" &
