#!/usr/bin/env sh

MOD="$2"
ALT="$3"
TERM="$4"

if [ "$1" = "qwerty" ]; then
    LEFT='h'
    DOWN='j'
    UP='k'
    RIGHT='l'

    RETURN="Semicolon"
    SCRATCH="n"

    SPLITV='u'
    SPLITH='o'

elif [ "$1" = "colemak" ]; then
    LEFT='m'
    DOWN='n'
    UP='e'
    RIGHT='i'

    RETURN='o'
    SCRATCH="h"

    SPLITV='l'
    SPLITH='y'
else
    echo "Valid options: qwerty, colemak" && exit
fi

# keybinds
swaymsg "bindsym $MOD+$SPLITH splith" &
swaymsg "bindsym $MOD+$SPLITV splitv" &
# term
swaymsg "bindsym $MOD+$RETURN exec $TERM" &
# navigation
swaymsg "bindsym $MOD+$LEFT focus left" &
swaymsg "bindsym $MOD+$DOWN focus down" &
swaymsg "bindsym $MOD+$UP focus up" &
swaymsg "bindsym $MOD+$RIGHT focus right" &
swaymsg "bindsym $MOD+Shift+$LEFT move left 50px" &
swaymsg "bindsym $MOD+Shift+$DOWN move down 50px" &
swaymsg "bindsym $MOD+Shift+$UP move up 50px" &
swaymsg "bindsym $MOD+Shift+$RIGHT move right 50px" &
# layout stuff
swaymsg "bindsym $MOD+Control+t splitt" &
# resizing
swaymsg "bindsym $MOD+$ALT+$LEFT  resize shrink width  50px" &
swaymsg "bindsym $MOD+$ALT+$DOWN  resize grow   height 50px" &
swaymsg "bindsym $MOD+$ALT+$UP    resize shrink height 50px" &
swaymsg "bindsym $MOD+$ALT+$RIGHT resize grow   width  50px" &
#
swaymsg "bindsym $MOD+Shift+$SCRATCH move scratchpad" &
swaymsg "bindsym $MOD+$SCRATCH scratchpad show" &
