#!/usr/bin/env sh

TARGET="$(printf "qwerty\ncolemak" | "$XDG_CONFIG_HOME"/sway/scripts/general_menu.sh)"

if [ "$TARGET" = "qwerty" ]; then
    "$XDG_CONFIG_HOME"/sway/scripts/binds qwerty Mod4 Mod1 foot &
    notify-send "qwerty keybinds loaded"
elif [ "$TARGET" = "colemak" ]; then
    "$XDG_CONFIG_HOME"/sway/scripts/binds colemak Mod4 Mod1 foot &
    notify-send "colemak keybinds loaded"
fi
