#!/usr/bin/env bash

dbus-update-activation-environment \
    --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &

mod="Mod4"
alt="Mod1"

# Reload
riverctl map normal $mod+$alt R spawn "$XDG_CONFIG_HOME/river/init" &
# Quit
riverctl map normal $mod+$alt Q exit &

SLURPCOMMAND="slurp -d -b '${CLR_07}40' -c '${CLR_07}' -w 3"

# laptop-specific configuration
if [[ $(cat /proc/sys/kernel/hostname) == "thonkpad" ]]; then
    WDPI=2

    riverctl map normal None XF86MonBrightnessUp spawn \
        "brightnessctl set +3%" &
    riverctl map normal None XF86MonBrightnessDown spawn \
        "brightnessctl set 3%-" &
    riverctl map locked None XF86MonBrightnessUp spawn \
        "brightnessctl set +3%" &
    riverctl map locked None XF86MonBrightnessDown spawn \
        "brightnessctl set 3%-" &

    wlr-randr --output "eDP-1" --scale "$WDPI" &

    TOUCHPAD="pointer-1739-52824-SYNA8008:00_06CB:CE58_Touchpad"
    riverctl input "$TOUCHPAD" click-method clickfinger &
    riverctl input "$TOUCHPAD" disable-while-typing enabled &
    riverctl input "$TOUCHPAD" natural-scroll enabled &
    riverctl input "$TOUCHPAD" tap enabled &
    riverctl input "$TOUCHPAD" tap-button-map left-right-middle &

    KEYBOARD="keyboard-4661-22137-My_KMonad_output"
    # riverctl keyboard-layout -options "compose:caps" "us" &

    left="H"
    down="J"
    up="K"
    right="L"
    ret="Semicolon"
    home="Y"
    end="O"
    pagedown="U"
    pageup="I"
    hide="M"

    BORDER_WIDTH=4

# desktop-specific configuration
elif [ "$(cat /proc/sys/kernel/hostname)" = "pc" ]; then
    WDPI=2

    wlr-randr --output "DP-3" --scale "$WDPI" &

    MOUSE="pointer-1133-50504-Logitech_USB_Receiver_Mouse"
    riverctl input "$MOUSE" accel-profile flat &

    left="M"
    down="N"
    up="E"
    right="I"
    ret="O"
    home="J"
    end="Y"
    pagedown="L"
    pageup="U"
    hide="H"

    BORDER_WIDTH=3
fi

pkill waybar; waybar &

#                  _  __ _      _         _            _                      _
#  ____ __  ___ __(_)/ _(_)__  | |_ ___  | |_____ _  _| |__  ___  __ _ _ _ __| |
# (_-< '_ \/ -_) _| |  _| / _| |  _/ _ \ | / / -_) || | '_ \/ _ \/ _` | '_/ _` |
# /__/ .__/\___\__|_|_| |_\__|  \__\___/ |_\_\___|\_, |_.__/\___/\__,_|_| \__,_|
#    |_|                                          |__/
#  _                    _
# | |__ _ _  _ ___ _  _| |_
# | / _` | || / _ \ || |  _|
# |_\__,_|\_, \___/\_,_|\__|
#         |__/
#
offset_amount=100
riverctl map normal $mod $ret spawn $TERMINAL &
# focus the next/previous view in the layout stack
riverctl map normal $mod $down focus-view next &
riverctl map normal $mod $up focus-view previous &
# swap the focused view with the next/previous view in the layout stack
riverctl map normal $mod+Shift $down swap next &
riverctl map normal $mod+Shift $up swap previous &
# decrease/increase the main_factor value of rivertile by 0.05
riverctl map normal $mod $right send-layout-cmd rivertile "main-ratio +0.05" &
riverctl map normal $mod $left send-layout-cmd rivertile "main-ratio -0.05" &
# increment/decrement the main_count value of rivertile.
riverctl map normal $mod+Shift $left send-layout-cmd \
    rivertile "main-count +1" &
riverctl map normal $mod+Shift $right send-layout-cmd \
    rivertile "main-count -1" &
# move views
riverctl map normal $mod+Shift Left move left $offset_amount &
riverctl map normal $mod+Shift Down move down $offset_amount &
riverctl map normal $mod+Shift Up move up $offset_amount &
riverctl map normal $mod+Shift Right move right $offset_amount &
# snap views to screen edges
riverctl map normal $mod+Control Left snap left &
riverctl map normal $mod+Control Down snap down &
riverctl map normal $mod+Control Up snap up &
riverctl map normal $mod+Control Right snap right &
# resize views
riverctl map normal $mod+$alt Left resize horizontal -$offset_amount &
riverctl map normal $mod+$alt Down resize vertical $offset_amount &
riverctl map normal $mod+$alt Up resize vertical -$offset_amount &
riverctl map normal $mod+$alt Right resize horizontal $offset_amount &
# swap current view with master, or master with first slave
riverctl map normal $mod $pageup zoom &
# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Left  send-layout-cmd \
    rivertile "main-location left" &
riverctl map normal $mod Down  send-layout-cmd \
    rivertile "main-location bottom" &
riverctl map normal $mod Up    send-layout-cmd \
    rivertile "main-location top" &
riverctl map normal $mod Right send-layout-cmd \
    rivertile "main-location right" &

#
#              _                          _
#  _   _ _ __ (_)_   _____ _ __ ___  __ _| |
# | | | | '_ \| \ \ / / _ \ '__/ __|/ _` | |
# | |_| | | | | |\ V /  __/ |  \__ \ (_| | |
#  \__,_|_| |_|_| \_/ \___|_|  |___/\__,_|_|
#
#  _     _           _ _
# | |__ (_)_ __   __| (_)_ __   __ _ ___
# | '_ \| | '_ \ / _` | | '_ \ / _` / __|
# | |_) | | | | | (_| | | | | | (_| \__ \
# |_.__/|_|_| |_|\__,_|_|_| |_|\__, |___/
#                              |___/
#
# terminal
riverctl map normal $mod Return spawn $TERMINAL &

# browsers
riverctl map normal $mod B spawn "MOZ_ENABLE_WAYLAND=1 firefox" &
riverctl map normal $mod+$alt B spawn "qutebrowser" &

# menu
riverctl map normal $mod D spawn "$XDG_CONFIG_HOME/sway/scripts/menu.sh" &

# files
riverctl map normal $mod A spawn "$FILES" &

# Mod+w to close the focused view
riverctl map normal $mod W close &

# Mod+x for swaylock
riverctl map normal $mod X spawn "$XDG_CONFIG_HOME/sway/scripts/swaylock.sh" &

# Mod+Tab between the two most recent tags, with Shift to send window there
riverctl map normal $mod Tab focus-previous-tags &
riverctl map normal $mod+Shift Tab send-to-previous-tags &

# temperature control
riverctl map normal $mod+$alt T spawn \
    "$XDG_CONFIG_HOME/sway/scripts/screen_temp.sh" &

# screenshots
riverctl map normal $mod+Shift D spawn "${SLURPCOMMAND} | grim -g - \
    ~/Pictures/\$(date +%Y-%m-%d-%H:%M:%S).png" &
riverctl map normal $mod+Shift S spawn "${SLURPCOMMAND} | \
    grim -g - /tmp/screenshot.png && \
    cat /tmp/screenshot.png | wl-copy -t image/png" &
riverctl map normal $mod+$alt D spawn \
    "grim ~/Pictures/\$(date +%Y-%m-%d-%H:%M:%S).png" &
riverctl map normal $mod+$alt S spawn "grim /tmp/screenshot.png && \
    cat /tmp/screenshot.png | wl-copy -t image/png" &

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view &

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view &

TAG_NUMBER=9
for i in $(seq 1 $TAG_NUMBER)
do
    tags=$((1 << (i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod "$i" set-focused-tags $tags &

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift "$i" set-view-tags $tags &

    # Mod+Alt+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+$alt "$i" toggle-focused-tags $tags &

    # Mod+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Control "$i" toggle-view-tags $tags &
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags &
riverctl map normal $mod+Shift 0 set-view-tags $all_tags &

# Mod+S to toggle float
riverctl map normal $mod S toggle-float &

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen &
riverctl map normal $mod+Shift F send-layout-cmd \
    rivertile "main-location monocle" &

# scratchpad
# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad with Super+P
riverctl map normal $mod $hide toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map normal $mod+Shift $hide set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}


# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume spawn \
        "pulsemixer --change-volume +10" &
    riverctl map $mode None XF86AudioLowerVolume spawn \
        "pulsemixer --change-volume -10" &
    riverctl map $mode None XF86AudioMute        spawn \
        "pulsemixer --toggle-mute" &
done

# Set repeat rate
riverctl set-repeat 50 200 &

riverctl rule-add float -app-id "*float*" &
riverctl rule-add float -app-id "*popup*" &
riverctl rule-add ssd -app-id firefox &
riverctl rule-add ssd -app-id io.elementary.files &
riverctl rule-add ssd -app-id org.pwmt.zathura &

riverctl attach-mode top &

# hide cursor when typing or after ten seconds of inactivity
riverctl hide-cursor timeout 10000 &
riverctl hide-cursor when-typing enabled &
# binding to toggle this behaviour (it interferes with mouse control in games)
riverctl map normal $mod+Shift V spawn \
    "riverctl hide-cursor timeout 0 && \
     riverctl hide-cursor when-typing disabled" &
riverctl map normal $mod V spawn \
    "riverctl hide-cursor timeout 10000 && \
     riverctl hide-cursor when-typing enabled" &

"$XDG_CONFIG_HOME"/river/wp "$CLR_07" &
riverctl map normal $mod+$alt B spawn "$XDG_CONFIG_HOME/river/wp" &

# Theming
BORDER_FOCUSED=$CLR_FG
BORDER_UNFOCUSED=$BG
BORDER_URGENT=$CLR_01
riverctl border-color-focused "0x$BORDER_FOCUSED" &
riverctl border-color-urgent "0x$BORDER_URGENT" &
riverctl border-width $BORDER_WIDTH &
riverctl xcursor-theme Adwaita 24 &

# Screen temperature
pkill wlsunset
"$XDG_CONFIG_HOME"/sway/scripts/screen_temp.sh default &

# # Superuser authentication popup
# /run/current-system/sw/libexec/polkit-gnome-authentication-agent-1 &

gsettings set org.gnome.desktop.wm.preferences titlebar-font "$FONT_SANS 12" &
gsettings set org.gnome.desktop.interface font-name "$FONT_SANS 12" &
gsettings set org.gnome.desktop.interface document-font-name "$FONT_SANS 12" &
gsettings set org.gnome.desktop.interface monospace-font-name "$FONT_MONO 12" &

# Gaps
DEFAULT_GAPS_OUTER=5 
DEFAULT_GAPS_INNER=5
riverctl default-layout rivertile &
pkill rivertile
rivertile \
    -outer-padding "$DEFAULT_GAPS_OUTER" \
    -view-padding "$DEFAULT_GAPS_INNER" \
    -main-ratio 0.5 \
    &
