#!/usr/bin/env bash

source "$XDG_CONFIG_HOME"/sh/env.sh
source "$XDG_CONFIG_HOME"/sh/aliases_funcs.sh

# fixes xdg-desktop-portal bug causing GTK apps to launch very slowly
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &

WFG="$(wq foreground)"
WBG="$(wq background)"
W00="$(wq color0)"
W01="$(wq color1)"
W02="$(wq color2)"
W03="$(wq color3)"
W04="$(wq color4)"
W05="$(wq color5)"
W06="$(wq color6)"
W07="$(wq color7)"
W08="$(wq color8)"
W15="$(wq color15)"

WSFG="$(wqs foreground)"
WSBG="$(wqs background)"
WS00="$(wqs color0)"
WS01="$(wqs color1)"
WS02="$(wqs color2)"
WS03="$(wqs color3)"
WS04="$(wqs color4)"
WS05="$(wqs color5)"
WS06="$(wqs color6)"
WS07="$(wqs color7)"
WS08="$(wqs color8)"
WS15="$(wqs color15)"

mod="Mod4"
alt="Mod1"

# Reload
riverctl map normal $mod+$alt R spawn "$XDG_CONFIG_HOME/river/init" &
# Quit
riverctl map normal $mod+$alt Q exit &

SLURPCOMMAND="slurp -d -b '${WS07}40' -c '${WS07}' -w 3"

# laptop-specific configuration
if [[ $(cat /proc/sys/kernel/hostname) == "thonkpad" ]]; then
    WDPI=2

    riverctl map normal None XF86MonBrightnessUp spawn "brightnessctl set +5%" &
    riverctl map normal None XF86MonBrightnessDown spawn "brightnessctl set 5%-" &
    riverctl map locked None XF86MonBrightnessUp spawn "brightnessctl set +5%" &
    riverctl map locked None XF86MonBrightnessDown spawn "brightnessctl set 5%-" &

    wlr-randr --output "eDP-1" --scale "$WDPI" &

    TOUCHPAD="pointer-1739-52824-SYNA8008:00_06CB:CE58_Touchpad"
    riverctl input "$TOUCHPAD" click-method clickfinger &
    riverctl input "$TOUCHPAD" disable-while-typing enabled &
    riverctl input "$TOUCHPAD" natural-scroll enabled &
    riverctl input "$TOUCHPAD" tap enabled &
    riverctl input "$TOUCHPAD" tap-button-map left-right-middle &

    riverctl map normal $mod+$alt B spawn "notify-send \$(cat /sys/class/power_supply/BAT0/capacity)%" &

    left="H"
    down="J"
    up="K"
    right="L"
    ret="Semicolon"
    home="Y"
    end="O"
    pagedown="U"
    pageup="I"
    hide="M"

    pkill waybar
    waybar -c "$XDG_CONFIG_HOME"/waybar/river_thinkpad.json &

# desktop-specific configuration
elif [[ "$(cat /proc/sys/kernel/hostname)" == "nixbtw" ]]; then

    WDPI="1.3"

    wlr-randr --output "DP-2" --scale "$WDPI" &

    MOUSE="pointer-1133-50504-Logitech_USB_Receiver_Mouse"
    riverctl input "$MOUSE" accel-profile flat &
    riverctl input "$MOUSE" natural-scroll enabled &

    left="M"
    down="N"
    up="E"
    right="I"
    ret="O"
    home="J"
    end="Y"
    pagedown="L"
    pageup="U"
    hide="H"
fi
#                  _  __ _      _         _            _                      _
#  ____ __  ___ __(_)/ _(_)__  | |_ ___  | |_____ _  _| |__  ___  __ _ _ _ __| |
# (_-< '_ \/ -_) _| |  _| / _| |  _/ _ \ | / / -_) || | '_ \/ _ \/ _` | '_/ _` |
# /__/ .__/\___\__|_|_| |_\__|  \__\___/ |_\_\___|\_, |_.__/\___/\__,_|_| \__,_|
#    |_|                                          |__/
#  _                    _
# | |__ _ _  _ ___ _  _| |_
# | / _` | || / _ \ || |  _|
# |_\__,_|\_, \___/\_,_|\__|
#         |__/
#
offset_amount=100
riverctl map normal $mod $ret spawn $TERMINAL &
# focus the next/previous view in the layout stack
riverctl map normal $mod $down focus-view next &
riverctl map normal $mod $up focus-view previous &
# swap the focused view with the next/previous view in the layout stack
riverctl map normal $mod+Shift $down swap next &
riverctl map normal $mod+Shift $up swap previous &
# decrease/increase the main_factor value of rivertile by 0.05
riverctl map normal $mod $right send-layout-cmd rivercarro "main-ratio +0.05" &
riverctl map normal $mod $left send-layout-cmd rivercarro "main-ratio -0.05" &
# increment/decrement the main_count value of rivertile.
riverctl map normal $mod+Shift $left send-layout-cmd rivercarro "main-count +1" &
riverctl map normal $mod+Shift $right send-layout-cmd rivercarro "main-count -1" &
# move views
riverctl map normal $mod+Shift Left move left $offset_amount &
riverctl map normal $mod+Shift Down move down $offset_amount &
riverctl map normal $mod+Shift Up move up $offset_amount &
riverctl map normal $mod+Shift Right move right $offset_amount &
# snap views to screen edges
riverctl map normal $mod+Control Left snap left &
riverctl map normal $mod+Control Down snap down &
riverctl map normal $mod+Control Up snap up &
riverctl map normal $mod+Control Right snap right &
# resize views
riverctl map normal $mod+$alt Left resize horizontal -$offset_amount &
riverctl map normal $mod+$alt Down resize vertical $offset_amount &
riverctl map normal $mod+$alt Up resize vertical -$offset_amount &
riverctl map normal $mod+$alt Right resize horizontal $offset_amount &
# swap current view with master, or master with first slave
riverctl map normal $mod $pageup zoom &
# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Left  send-layout-cmd rivercarro "main-location left" &
riverctl map normal $mod Down  send-layout-cmd rivercarro "main-location bottom" &
riverctl map normal $mod Up    send-layout-cmd rivercarro "main-location top" &
riverctl map normal $mod Right send-layout-cmd rivercarro "main-location right" &

#
#              _                          _
#  _   _ _ __ (_)_   _____ _ __ ___  __ _| |
# | | | | '_ \| \ \ / / _ \ '__/ __|/ _` | |
# | |_| | | | | |\ V /  __/ |  \__ \ (_| | |
#  \__,_|_| |_|_| \_/ \___|_|  |___/\__,_|_|
#
#  _     _           _ _
# | |__ (_)_ __   __| (_)_ __   __ _ ___
# | '_ \| | '_ \ / _` | | '_ \ / _` / __|
# | |_) | | | | | (_| | | | | | (_| \__ \
# |_.__/|_|_| |_|\__,_|_|_| |_|\__, |___/
#                              |___/
#
# terminal
riverctl map normal $mod Return spawn $TERMINAL &

# browsers
riverctl map normal $mod B spawn "MOZ_ENABLE_WAYLAND=1 firefox" &

# menu
riverctl map normal $mod D spawn "$XDG_CONFIG_HOME/sway/scripts/menu.sh" &

# files
riverctl map normal $mod A spawn "$FILES" &

# Mod+w to close the focused view
riverctl map normal $mod W close &

# Mod+x for swaylock
riverctl map normal $mod X spawn "$XDG_CONFIG_HOME/sway/scripts/swaylock.sh" &

# Mod+Tab between the two most recent tags, with Shift to send window there
riverctl map normal $mod Tab focus-previous-tags &
riverctl map normal $mod+Shift Tab send-to-previous-tags &

# temperature control
riverctl map normal $mod+$alt T spawn "$XDG_CONFIG_HOME/sway/scripts/screen_temp.sh" &

# screenshots
riverctl map normal $mod+Shift D spawn "${SLURPCOMMAND} | grim -g - \
    ~/Pictures/screenshots/\$(date +%Y-%m-%d-%H:%M:%S).png && notify-send 'Saved screenshot to ~/Pictures/screenshots/'" &
riverctl map normal $mod+Shift S spawn "${SLURPCOMMAND} | grim -g - /tmp/screenshot.png && \
    cat /tmp/screenshot.png | wl-copy -t image/png" &
riverctl map normal $mod+$alt D spawn "grim \
   ~/Pictures/screenshots/\$(date +%Y-%m-%d-%H:%M:%S).png && notify-send 'Saved screenshot to ~/Pictures/screenshots/'" &
riverctl map normal $mod+$alt S spawn "grim /tmp/screenshot.png && \
    cat /tmp/screenshot.png | wl-copy -t image/png" &

# # Mod+Period and Mod+Comma to focus the next/previous output
# riverctl map normal $mod Period focus-output next
# riverctl map normal $mod Comma focus-output previous
# # Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
# riverctl map normal $mod+Shift Period send-to-output next
# riverctl map normal $mod+Shift Comma send-to-output previous
# Mod+Return to bump the focused view to the top of the layout stack
#riverctl map normal $mod Return zoom

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view &

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view &

TAG_NUMBER=4
for i in $(seq 1 $TAG_NUMBER)
do
    tags=$((1 << (i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod "$i" set-focused-tags $tags &

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift "$i" set-view-tags $tags &

    # Mod+Alt+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+$alt "$i" toggle-focused-tags $tags &

    # Mod+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Control "$i" toggle-view-tags $tags &
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags &
riverctl map normal $mod+Shift 0 set-view-tags $all_tags &

# Mod+S to toggle float
riverctl map normal $mod S toggle-float &

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen &
riverctl map normal $mod+Shift F send-layout-cmd rivercarro "main-location monocle" &

# # Mod+Shift+B to fetch random wallpaper
# riverctl map normal $mod+Shift B spawn "${XDG_CONFIG_HOME}/sway/scripts/randwall.sh ~/dotfiles/Pictures/cafe-walls" &

# Mod+Alt+Shift+B to kill swaybg and get back solid colour background
riverctl map normal $mod+${alt}+Shift B spawn "killall -q swaybg" &

# scratchpad
# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad with Super+P
riverctl map normal $mod $hide toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map normal $mod+Shift $hide set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}


# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn "pulsemixer --change-volume +10" &
    riverctl map $mode None XF86AudioLowerVolume  spawn "pulsemixer --change-volume -10" &
    riverctl map $mode None XF86AudioMute         spawn "pulsemixer --toggle-mute" &
done

# Set repeat rate
riverctl set-repeat 50 200 &

# Set app-ids of views which should float
riverctl rule-add float -app-id "*float*" &
riverctl rule-add float -app-id "*popup*" &

# Set app-ids of views which should use server-side decorations
riverctl rule-add ssd -app-id firefox &
riverctl rule-add ssd -app-id io.elementary.files &

riverctl attach-mode top &
# hide cursor when typing or after ten seconds of inactivity
riverctl hide-cursor timeout 10000 &
riverctl hide-cursor when-typing enabled &
# binding to toggle this behaviour (it interferes with mouse control in games)
riverctl map normal $mod+Shift V spawn \
    "riverctl hide-cursor timeout 0 && \
     riverctl hide-cursor when-typing disabled && \
     notify-send 'Disabled cursor hiding'" &
riverctl map normal $mod V spawn \
    "riverctl hide-cursor timeout 10000 && \
     riverctl hide-cursor when-typing enabled && \
     notify-send 'Enabled cursor hiding'" &

# Background
BG="$WS08"
riverctl background-color "0x$BG" &
# "$XDG_CONFIG_HOME"/sway/scripts/randwall.sh ~/dotfiles/Pictures/cafe-walls &

# Theming
BORDER_FOCUSED=$WSFG
BORDER_UNFOCUSED=$BG
BORDER_URGENT=$WS01
BORDER_WIDTH=3
riverctl border-color-focused "0x$BORDER_FOCUSED" &
riverctl border-color-unfocused "0x$BORDER_UNFOCUSED" &
riverctl border-color-urgent "0x$BORDER_URGENT" &
riverctl border-width $BORDER_WIDTH &
riverctl xcursor-theme Adwaita 24 &

# Screen temperature
pkill wlsunset
"$XDG_CONFIG_HOME"/sway/scripts/screen_temp.sh default &

# Superuser authentication popup
/run/current-system/sw/libexec/polkit-gnome-authentication-agent-1 &

# Notifications
riverctl map normal $mod C spawn "dunstctl close" &
riverctl map normal $mod+Shift C spawn "dunstctl close-all" &
riverctl map normal $mod+$alt C spawn "dunstctl history-pop" &
pkill dunst; dunst &

# Gaps
DEFAULT_GAPS_OUTER=10 
DEFAULT_GAPS_INNER=10
riverctl default-layout rivercarro &
pkill rivercarro
rivercarro -outer-gaps "$DEFAULT_GAPS_OUTER" -inner-gaps "$DEFAULT_GAPS_INNER" -no-smart-gaps &
riverctl map normal $mod G send-layout-cmd rivercarro "gaps +10" &
riverctl map normal $mod+Shift G send-layout-cmd rivercarro "gaps -10" &
riverctl map normal $mod Period send-layout-cmd rivercarro "outer-gaps +10" &
riverctl map normal $mod+Shift Period send-layout-cmd rivercarro "outer-gaps -10" &
resetgaps="\
    riverctl send-layout-cmd rivercarro 'outer-gaps $DEFAULT_GAPS_OUTER' & \
    riverctl send-layout-cmd rivercarro 'inner-gaps $DEFAULT_GAPS_INNER' & \
"
riverctl map normal $mod+$alt G spawn "$resetgaps" &

# # Tag overlay
# killall -q river-tag-overlay
# river-tag-overlay \
#     --border-width $BORDER_WIDTH \
#     --tag-amount $TAG_NUMBER \
#     --tags-per-row $TAG_NUMBER \
#     --square-size 36 \
#     --square-padding 25 \
#     --square-inner-padding 9 \
#     --square-border-width 0 \
#     --background-colour 0x$WSBG \
#     --border-colour 0x$WS00 \
#     --square-active-background-colour 0x$BORDER_FOCUSED \
#     --square-active-occupied-colour 0x$WS05 \
#     --square-inactive-background-colour 0x$WS08 \
#     --square-inactive-occupied-colour 0x$WS00 \
#     --square-urgent-background-colour 0x$WS01 \
#     --square-urgent-occupied-colour 0x$BORDER_FOCUSED \
#     --anchors 0:0:1:0 \
#     --margins 0:0:100:0 \
#     &
