require('vis')
vis.events.subscribe(vis.events.INIT, function()
	vis:command("set theme custom")
    vis:command("set escdelay 0")
    vis:command("set tabwidth 4")
    vis:command("set expandtab on")
    vis:command("set syntax off")
    vis:command("set ignorecase on")
    vis:command("set autoindent on")
    vis:command("map! normal p \"+<Print>")
    vis:command("map! visual ")
    vis:command("map! visual-line ")
    vis:command("map! operator-pending ")
    vis:command("map! normal y \"+<Copy>")
    vis:command("map! visual ")
    vis:command("map! visual-line ")
    vis:command("map! operator-pending ")
    vis:command("map! normal <Left> h")
    vis:command("map! visual ")
    vis:command("map! visual-line ")
    vis:command("map! operator-pending ")
    vis:command("map! normal <Down> j")
    vis:command("map! visual ")
    vis:command("map! visual-line ")
    vis:command("map! operator-pending ")
    vis:command("map! normal <Up> k")
    vis:command("map! visual ")
    vis:command("map! visual-line ")
    vis:command("map! operator-pending ")
    vis:command("map! normal <Right> l")
    vis:command("map! visual ")
    vis:command("map! visual-line ")
    vis:command("map! operator-pending ")
end)

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
    -- vis:command("set cursorline on")
end)
