# based on solarized_dark theme by:
# Author: NNB <nnbnh@protonmail.com>

"attribute" = { fg = "magenta" }
"keyword" = { fg = "magenta" }
"keyword.directive" = { fg = "red" }
"namespace" = { fg = "magenta" }
"operator" = { }
"special" = { fg = "magenta" }
"variable.builtin" = { fg = "cyan", modifiers = ["bold"] }
"variable.function" = { fg = "blue" }
"type" = { fg = "yellow" }
"type.builtin" = { fg = "yellow" }
"constructor" = { fg = "blue" }
"function" = { fg = "blue" }
"function.macro" = { fg = "magenta" }
"function.builtin" = { fg = "blue", modifiers = ["bold"] }
"function.special" = { fg = "magenta" }
"comment" = { fg = "green", modifiers = ["italic"] }
"string" = { fg = "cyan" }
"constant" = { fg = "cyan" }
"constant.builtin" = { fg = "cyan", modifiers = ["bold"] }
"constant.character.escape" = { fg = "yellow", modifiers = ["bold"] }
"label" = { fg = "white" }
"module" = { fg = "magenta" }
"tag" = { fg = "magenta" }

"markup.heading" = "blue"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = "cyan"
"markup.raw" = "green"

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "magenta" }
"diff.minus" = { fg = "red" }

"ui.background" = {}

"ui.virtual.whitespace" = { fg = "gray" }

"ui.linenr" = { fg = "light-gray", bg = "black" }
"ui.linenr.selected" = { fg = "white", modifiers = ["bold"] }
"ui.cursorline" = {}

"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.normal" = { fg = "blue", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "cyan", modifiers = ["bold"] }

"ui.statusline.inactive" = { fg = "white", bg = "black" }

"ui.popup" = { bg = "black" }
"ui.menu.selected" = { fg = "black", bg = "white"}
"ui.menu" = { fg = "white", bg = "black" }
"ui.window" = { fg = "white" }
"ui.help" = { modifiers = ["reversed"] }

"ui.popup.info" = {fg = "black", bg = "white", modifiers = ["bold"]}
"ui.text.info" = {fg = "black", modifiers = ["bold"]}

"ui.text" = { fg = "white" }
"ui.text.focus" = { fg = "blue", modifiers = ["bold"]}
"ui.highlight" = { fg = "red", modifiers = ["bold", "italic", "underlined"] }

"ui.cursor.primary" = { fg = "black", bg = "white" }
"ui.cursor.select" = { fg = "black", bg = "cyan" }
"ui.cursorline.primary" = { bg = "black" }
"ui.cursorline.secondary" = { bg = "black" }

"ui.selection" = { bg = "gray" }
"ui.selection.primary" = { bg = "gray" }

"ui.virtual.indent-guide" = { fg = "black" }
"ui.virtual.ruler" = { fg = "red" }

"ui.cursor" = {fg = "black", bg = "cyan"}
"ui.cursor.insert" = {fg = "black", bg = "white"}
"ui.cursor.match" = { fg = "black", bg = "gray" }

"warning" =  { fg = "magenta", modifiers= ["bold", "underlined"] }
"error" = { fg = "red", modifiers= ["bold", "underlined"] }
"info" = { fg = "blue", modifiers= ["bold", "underlined"] }
"hint" = { fg = "gray", modifiers= ["bold", "underlined"] }

"diagnostic.warning" = { underline = { style = "curl", color = "magenta" } }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"diagnostic.info" = { underline = { style = "curl", color = "blue" } }
"diagnostic.hint" = { underline = { style = "curl", color = "gray" } }
