# based on official helix base16_terminal theme by
# Author: NNB <nnbnh@protonmail.com>

"ui.menu" = { fg = "white", bg = "black" }
"ui.menu.selected" = { fg = "white", bg = "gray", modifiers = ["reversed"] }
"ui.linenr" = { fg = "gray" }
"ui.popup" = { bg = "black" }
"ui.window" = { bg = "black" }
"ui.linenr.selected" = "light-gray"
"ui.selection" = { fg = "gray", modifiers = ["reversed"] }
"ui.cursorline" = { bg = "black" }
"comment" = "green"
"string"  = "cyan"
"ui.statusline" = { fg = "white", bg = "black" }
# "ui.statusline.normal" = { fg = "black", bg = "blue" }
# "ui.statusline.insert" = { fg = "black", bg = "green" }
# "ui.statusline.select" = { fg = "black", bg = "cyan" }
"ui.statusline.inactive" = { fg = "gray", bg = "black" }
"ui.help" = { fg = "white", bg = "black" }
"ui.cursor" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.virtual" = "light-gray"
"ui.virtual.indent-guide" = "black"

# "constant.numeric" = "cyan"
# "constant" = "cyan"
# "constant.builtin" = "cyan"
# "keyword" = "blue"
# "function" = { modifiers = ["bold"] }

# "attributes" = "yellow"
# "type" = { fg = "pink" }
# "type.builtin" = { fg = "pink" }
# "ui.cursor.match" = { fg = "light-yellow", modifiers = ["underlined"] }
# "constant.character.escape" = "magenta"
# "function.macro" = "pink"
# "function.special" = { fg = "pink" }
# "tag" = { fg = "pink" }
# "constructor" = "light-blue"
# "special" = "light-blue"
# "label" = "light-magenta"
# "namespace" = "blue"

# "markup.heading" = "light-blue"
# "markup.list" = "light-red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
# "markup.link.text" = "light-red"
# "markup.quote" = "light-cyan"
# "markup.raw" = "light-green"

# "diff.plus" = "light-green"
# "diff.delta" = "yellow"
# "diff.minus" = "light-red"

"diagnostic" = { modifiers = ["underlined"] }
# "ui.gutter" = { bg = "" }
"info" = "light-blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "light-red"

"punctuation" = "light-gray"
"punctuation.delimiter" = "light-gray"
