# based on official helix base16_terminal theme by
# Author: NNB <nnbnh@protonmail.com>

"ui.menu" = { fg = "white", bg = "black" }
"ui.menu.selected" = { fg = "white", bg = "gray", modifiers = ["reversed"] }
"ui.linenr" = { fg = "gray" }
"ui.popup" = { bg = "black" }
"ui.window" = { bg = "black" }
"ui.linenr.selected" = { fg = "light-gray", modifiers = ["bold"] }
"ui.selection" = { fg = "gray", modifiers = ["reversed"] }
"comment" = { fg = "light-gray", modifiers = ["italic"] }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "gray", bg = "black" }
"ui.help" = { fg = "white", bg = "black" }
"ui.cursor" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.virtual" = "light-gray"

"variable" = "white"

"constant.numeric" = "orange"
"constant" = "cyan"
"constant.builtin" = { fg = "cyan", modifiers = ["bold"] }

"attributes" = "yellow"
"type" = { fg = "yellow", modifiers = ["italic"] }
"type.builtin" = { fg = "light-yellow", modifiers = ["bold"] }
"ui.cursor.match" = { fg = "light-yellow", modifiers = ["underlined"] }
"string"  = "green"
"variable.other.member" = "red"
"constant.character.escape" = "light-cyan"
"function" = "light-blue"
"function.macro" = { fg = "pink" }
"function.special" = { fg = "pink" }
"tag" = { fg = "pink" }
"constructor" = "light-blue"
"special" = "light-blue"
"keyword" = { fg = "magenta", modifiers = ["bold"] }
"label" = "light-magenta"
"namespace" = "blue"

"operator" = { fg = "cyan" }

"markup.heading" = "light-blue"
"markup.list" = "light-red"
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "pink", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "light-red"
"markup.quote" = "light-cyan"
"markup.raw" = "light-green"

"diff.plus" = "light-green"
"diff.delta" = "yellow"
"diff.minus" = "light-red"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "" }
"info" = "light-blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "light-red"

"punctuation" = "pink"
"punctuation.delimiter" = "pink"

[palette]
pink = "#cf4072"
orange = "#d64f15"
