# based on official helix base16_terminal theme by
# Author: NNB <nnbnh@protonmail.com>

"ui.menu" = { fg = "white", bg = "black" }
"ui.menu.selected" = { fg = "white", bg = "gray", modifiers = ["reversed"] }
"ui.linenr" = { fg = "gray" }
"ui.popup" = { bg = "black" }
"ui.window" = { bg = "black" }
"ui.linenr.selected" = "light-gray"
"ui.selection" = { fg = "gray", modifiers = ["reversed"] }
"ui.cursorline" = { bg = "black" }
"comment" = "green"
"string"  = "cyan"
"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "gray", bg = "black" }
"ui.help" = { fg = "white", bg = "black" }
"ui.cursor" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.virtual" = "light-gray"
"ui.virtual.indent-guide" = "black"

# "constant.numeric" = "cyan"
# "constant" = "cyan"
# "constant.builtin" = "cyan"
# "type" = { fg = "pink" }
# "type.builtin" = { fg = "pink" }
# "function" = "blue"
# "function.macro" = "pink"
# "function.special" = { fg = "pink" }
# "punctuation" = "light-gray"
# "punctuation.delimiter" = "light-gray"
# "keyword" = "magenta"

"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"diagnostic" = { modifiers = ["underlined"] }
"info" = "light-blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "light-red"

[palette]
pink = "#cf4072"
orange = "#d64f15"
