#!/bin/sh
while read file
do
    fullpath="$(pwd)/$file"
    case "$1" in
    "w")
        xwallpaper --zoom "$file" ;;
    "r")
        convert -rotate 90 "$file" "$file" ;;
    "R")
        convert -rotate -90 "$file" "$file" ;;
    "y")
        echo -n "$file" | xclip -selection clipboard &&
        notify-send "$file copied to clipboard" & ;;
    "Y")
        echo -n "$fullpath" | xclip -selection clipboard &&
        notify-send "$fullpath copied to clipboard" & ;;
    "d")
        [ "$(printf "n\\ny" | dmenu -i -p "Really delete $file?")" = "y" ] && rm "$file" && notify-send "$file deleted" & 
    esac
done
