[buildPlans.iosevka-custom]
family = "IosevkaCustom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom.variants.design]
    a = "double-storey-serifless"
    b = "toothed"
    g = "single-storey-serifless"
    i = "serifed"
    lower-alpha = "crossing"
    asterisk = "turn-hex-low"
    question = "corner"

    [buildPlans.iosevka-custom.variants.italic]
    capital-b = "standard-serifless"
    capital-q = "curly-tailed"
    capital-z = "curly-serifless-with-horizontal-crossbar"
    i = "tailed"
    z = "curly-serifless-with-horizontal-crossbar"

  [buildPlans.iosevka-custom.ligations]
  inherits = "dlig"

[buildPlans.iosevka-custom.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-custom.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.weights.extrabold]
shape = 800
menu = 800
css = 800

[buildPlans.iosevka-custom.weights.heavy]
shape = 900
menu = 900
css = 900
