bitrate = 320
shuffle = true
use_nerdfont = true
cover_max_scale = 2

[theme]
primary = "light white"
secondary = "light black"
title = "light white"
playing = "cyan"
playing_selected = "light green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "black"
error = "black"
error_bg = "red"
statusbar = "light white"
statusbar_progress = "black"
statusbar_bg = "black"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
