# disable inserting a blank line between shell prompts
add_newline = false
# some more symbols:
# ➜
# 
# 
# 
# Replace the default "❯" symbol:

command_timeout = 100

[character]
# success_symbol = "[](bold blue)[](bold yellow)[](bold red)"
# error_symbol   = "[](bold red)[](bold purple)[](bold red)"
success_symbol = "[λ](bold blue)"
error_symbol   = "[λ](bold purple)"

[git_status]
disabled = true # too slow
