#!/usr/bin/env sh

# possible preset values below
# you should use the slowest you have patience for, but the default,
# "medium", is perfectly fine for most use cases

# ultrafast
# superfast
# veryfast
# faster
# fast
# medium
# slow
# slower
# veryslow

# check enough arguments were supplied
[ $# -lt 2 ] && echo "Not enough arguments supplied" && exit

# set preset to default if not provided
[ -z "$3" ] && PRESET="medium"
# otherwise, set to argument 3
[ -n "$3" ] && PRESET="$3"

# ffmpeg is doing the actual work
ffmpeg -y -i "$1" -vf mpdecimate,setpts=N/FRAME_RATE/TB \
       -an -preset "$PRESET" "$2"
