theme = "base16_custom"

[editor]
line-number = "relative"
idle-timeout = 0
cursorline = true
color-modes = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "•"

[keys.normal]
c = "change_selection_noyank"
d = "delete_selection_noyank"
C-left = "jump_view_left"
C-right = "jump_view_right"
C-up = "jump_view_up"
C-down = "jump_view_down"
C-S-left = "swap_view_left"
C-S-right = "swap_view_right"
C-S-up = "swap_view_up"
C-S-down = "swap_view_down"
S-up = "move_line_up"
S-down = "move_line_down"
g = { left = "goto_first_nonwhitespace", right = "goto_line_end", h = "goto_first_nonwhitespace", l = "goto_line_end", j = "goto_last_accessed_file" }
V = "extend_line_down"
S-pageup = ":theme solarized_light"
S-pagedown = ":theme solarized_dark"
S-end = ":theme base16_custom"
C-r = "redo"
X = "extend_line_up"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
