theme = "base16_custom"

[editor]
line-number = "relative"
idle-timeout = 0
cursorline = true
color-modes = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = false
character = "•"

[keys.insert]
up = "move_line_up"
down = "move_line_down"
left = "move_char_left"
right = "move_char_right"
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
c = "change_selection_noyank"
d = "delete_selection_noyank"
C-left = "jump_view_left"
C-right = "jump_view_right"
C-up = "jump_view_up"
C-down = "jump_view_down"
C-S-left = "swap_view_left"
C-S-right = "swap_view_right"
C-S-up = "swap_view_up"
C-S-down = "swap_view_down"
S-up = "move_line_up"
S-down = "move_line_down"
g = { left = "goto_first_nonwhitespace", right = "goto_line_end", h = "goto_first_nonwhitespace", l = "goto_line_end", j = "goto_last_accessed_file" }
V = "extend_line_down"
S-pageup = ":theme solarized_light"
S-pagedown = ":theme solarized_dark"
S-end = ":theme base16_custom"
C-r = "redo"
X = "extend_line_up"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
C = ["collapse_selection", "extend_to_line_end", "change_selection"]
D = ["extend_to_line_end", "delete_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
"%" = "match_brackets"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
